import React, { useEffect, useRef, useState } from 'react';
import {createRoot} from 'react-dom/client';
import {Crosshair, ArrowUpRight, ChevronLeft, ChevronRight, Copy, Download, RotateCcw, Undo2, Play, Pause, X, Check, Bookmark, Star, Trash2, Search, Upload, SlidersHorizontal, Link, FileCode2, HelpCircle, Pencil, Plus, Maximize, Minimize} from 'lucide-react';
import {styles,defaults,styleFields,crosshairFields,presets,commands,autoexec,safeAlias,validateSettings,type Settings,type Field} from './model';
import {encode,decode,importCommands} from './codec';
import {Preview} from './Preview';
import {useDisplayEstimate} from './display';
import {downloadConfig} from './config-export';
import type { RenderStatus } from './preview-renderer';
import type { PreviewMode } from './preview-geometry';
import {copyText} from './clipboard';
import {read,write,validateLibrary,limitLibrary,type Saved} from './storage';
import './style.css';
import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';
import '@fontsource/jetbrains-mono/latin-400.css';

const maps=['dust2','nuke','mirage','ancient','anubis','cache','inferno'];
const mapNames=['Dust II','Nuke','Mirage','Ancient','Anubis','Cache','Inferno'];
function initial(): {settings:Settings;error?:string;note?:string}{
  try{
    const params=new URLSearchParams(location.search);
    const code=params.get('code')??params.get('crosshair')??(location.pathname.startsWith('/CS')?location.pathname.slice(1):null);
    if(code){const result=decode(code);const complete=params.get('settings');if(complete){const full=validateSettings(JSON.parse(complete));if(encode(full)!==encode(result.settings))throw Error('The link contains conflicting crosshair settings.');return {settings:full,note:result.note};}return {settings:result.settings,note:result.note};}
    const full=params.get('settings');if(full)return {settings:validateSettings(JSON.parse(full))};
    return {settings:{...validateSettings(read('draft',defaults)),cl_crosshair_recoil:0,cl_crosshair_friendly_warning:0}};
  }catch(error){return {settings:{...defaults},error:message(error)};}
}
function message(error:unknown){return error instanceof Error?error.message:'Something went wrong.';}
function download(text:string,name:string,type='text/plain') {const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

function NumberControl({field,value,onChange,disabled=false}: {field:Field;value:number;onChange:(value:number)=>void;disabled?:boolean}){
  const format=(n:number)=>(field.step??1)<1?n.toFixed(2):String(n);
  const [draft,setDraft]=useState(format(value));useEffect(()=>setDraft(format(value)),[value,field.step]);
  const commit=()=>{const n=Number(draft),step=field.step??1;if(draft.trim()&&Number.isFinite(n)){const clamped=Math.max(field.min??0,Math.min(field.max??255,n));const normalized=Number((Math.round(clamped/step)*step).toFixed(2));setDraft(format(normalized));onChange(normalized);}else setDraft(format(value));};
  return <div className="number-controls"><input type="range" aria-label={`${field.label} slider`} min={field.min} max={field.max} step={field.step??1} value={value} disabled={disabled} onChange={e=>onChange(Number(e.target.value))}/><input className="numeric" type="number" aria-label={field.label} min={field.min} max={field.max} step={field.step??1} value={draft} disabled={disabled} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></div>;
}
function Row({field,s,set}: {field:Field;s:Settings;set:(key:string,value:number)=>void}){return <div className="setting-row"><label htmlFor={field.key}>{field.label}{['Style','Thickness','Length','Gap'].includes(field.label)&&<small>{field.label==='Style'?'NEW':'UPDATED'}</small>}</label>{field.options?<select id={field.key} aria-label={field.label} value={s[field.key]} onChange={e=>set(field.key,Number(e.target.value))}>{field.options.map(([n,label])=><option key={n} value={n}>{label}</option>)}</select>:<NumberControl field={field} value={s[field.key]} onChange={value=>set(field.key,value)}/>}</div>;}
function ColorRow({outline=false,s,set}: {outline?:boolean;s:Settings;set:(key:string,value:number)=>void}){
  const [open,toggle]=useState(false);const prefix=outline?'cl_crosshairoutline_':'cl_crosshaircolor_';const label=outline?'Outline Color and Transparency':'Color and Transparency';
  const hex='#'+['r','g','b'].map(c=>s[prefix+c].toString(16).padStart(2,'0')).join('');
  return <><div className="setting-row"><span>{label}{!outline&&<small>UPDATED</small>}</span><button className="swatch" aria-label={`Edit ${label}`} aria-expanded={open} onClick={()=>toggle(!open)}><span style={{backgroundColor:hex,opacity:s[prefix+'a']/255}}/></button></div>{open&&<div className="color-panel"><div className="color-top"><input type="color" aria-label={outline?'Outline color':'Crosshair color'} value={hex} onChange={e=>['r','g','b'].forEach((c,i)=>set(prefix+c,parseInt(e.target.value.slice(1+i*2,3+i*2),16)))}/><code>{hex.toUpperCase()}</code><div className="color-presets">{['#00ff00','#00c8ff','#ffffff','#ffda22','#fa3250','#000000'].map(color=><button key={color} aria-label={`Set ${outline?'outline':'crosshair'} ${color}`} style={{backgroundColor:color}} onClick={()=>['r','g','b'].forEach((c,i)=>set(prefix+c,parseInt(color.slice(1+i*2,3+i*2),16)))}/>)}</div></div>{['r','g','b','a'].map((c,i)=><div className="setting-row compact" key={c}><span>{['Red','Green','Blue','Opacity'][i]}</span><NumberControl field={{key:prefix+c,label:`${outline?'Outline':'Crosshair'} ${['red','green','blue','opacity'][i]}`,min:0,max:255}} value={s[prefix+c]} onChange={n=>set(prefix+c,n)}/></div>)}</div>}</>;
}

function App(){
  const start=useRef(initial());const [s,setSettings]=useState(start.current.settings);const [undo,setUndo]=useState<Settings[]>([]);
  const [alias,setAlias]=useState(()=>read<string>('alias',''));const [map,setMap]=useState(0);const [zoom,setZoom]=useState(1);const [dynamic,setDynamic]=useState(false);const [previewMode,setPreviewMode]=useState<PreviewMode>('crosshair');
  const display=useDisplayEstimate();const [displayHeight,setDisplayHeight]=useState(0);const [displayHeightDraft,setDisplayHeightDraft]=useState<string|null>(null);const [fullscreen,setFullscreen]=useState(false);const mapRef=useRef<HTMLDivElement>(null);
  const [targetHeight,setTargetHeight]=useState(-1);const effectiveHeight=targetHeight===-1?(displayHeight||display.height):targetHeight;const [fit,setFit]=useState(false);const [phase,setPhase]=useState(0);const [inspectSplit,setInspectSplit]=useState(false);const [previewStatus,setPreviewStatus]=useState<RenderStatus>({clipped:false,scale:1});
  const [theme,setTheme]=useState(()=>read<string>('theme','cs2'));const [modal,setModal]=useState<'share'|'library'|'help'|null>(null);const [tab,setTab]=useState('all');
  const [toast,setToast]=useState(start.current.error??start.current.note??'');const [importText,setImportText]=useState('');const [importError,setImportError]=useState('');const [legacyHeight,setLegacyHeight]=useState(1080);
  const [library,setLibrary]=useState<Saved[]>(()=>{try{return validateLibrary(read('library',[]));}catch{return [];}});
  const [search,setSearch]=useState('');const [savedName,setSavedName]=useState('My crosshair');const [libraryFilter,setLibraryFilter]=useState('all');const [editing,setEditing]=useState<string|null>(null);
  const [guide,setGuide]=useState(()=>!read('guide-dismissed',false));const [rating,setRating]=useState(()=>read<number>('rating',0));const [note,setNote]=useState(()=>read<string>('feedback-note',''));
  const backupInput=useRef<HTMLInputElement>(null);const cfgInput=useRef<HTMLInputElement>(null);const dialogRef=useRef<HTMLDialogElement>(null);
  const code=encode(s);let aliasError='';try{safeAlias(alias);}catch(e){aliasError=message(e);}
  const notify=(text:string)=>setToast(text);
  useEffect(()=>{const update=()=>setFullscreen(document.fullscreenElement===mapRef.current);document.addEventListener('fullscreenchange',update);return()=>document.removeEventListener('fullscreenchange',update);},[]);
  const toggleFullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await mapRef.current?.requestFullscreen();}catch{notify('Fullscreen is unavailable in this browser. The inline preview remains usable.');}};
  useEffect(()=>{if(!write('draft',s))notify('Browser storage is unavailable. Export a config to keep your changes.');},[s]);
  useEffect(()=>{write('alias',alias);},[alias]);useEffect(()=>{if(!write('library',library))notify('Library could not be saved. Download a backup.');},[library]);
  useEffect(()=>{write('theme',theme);document.documentElement.dataset.theme=theme;},[theme]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),7000);return()=>clearTimeout(timer);},[toast]);
  useEffect(()=>{if(modal)dialogRef.current?.showModal();else dialogRef.current?.close();},[modal]);
  function change(key:string,value:number){setUndo(items=>[...items.slice(-29),s]);setSettings(prev=>({...prev,[key]:value}));}
  function load(settings:Settings){setUndo(items=>[...items.slice(-29),s]);setSettings({...settings});}
  function reset(){load({...defaults});notify('Crosshair reset to the studio defaults.');}
  function goBack(){if(!undo.length)return;setSettings(undo[undo.length-1]);setUndo(undo.slice(0,-1));}
  function remember(settings=s,name=styles.find(([id])=>id===settings.cl_crosshairstyle)?.[1]??'Crosshair',favorite=false){
    const entry:Saved={id:crypto.randomUUID(),name,settings:{...settings},alias:aliasError?'':alias.trim(),favorite,date:new Date().toISOString()};
    setLibrary(prev=>{const same=prev.find(item=>encode(item.settings)===encode(settings)&&JSON.stringify(item.settings)===JSON.stringify(settings));
      if(same)return prev.map(item=>item.id===same.id?{...item,name:favorite?name:item.name,alias:entry.alias,date:entry.date,favorite:favorite||item.favorite}:item);
      const next=[entry,...prev];return [...next.filter(item=>item.favorite).slice(0,50),...next.filter(item=>!item.favorite).slice(0,20)];});
  }
  async function copy(text:string,label:string){if(await copyText(text))notify(`${label} copied.`);else notify('Clipboard access failed. Select and copy the text in Share or Import.');}
  function exportCfg(){if(aliasError){notify(aliasError);return;}download(downloadConfig(s,alias),alias.trim()?`crosshair_${alias.trim()}.cfg`:'crosshair.cfg');remember();notify('Config downloaded.');}
  function shareLink(){const url=new URL('/',location.origin);url.searchParams.set('code',code);url.searchParams.set('settings',JSON.stringify(s));return url.toString();}
  function doImport(){try{let result;if(importText.trim().startsWith('CS')){const parsed=decode(importText,legacyHeight);result=parsed.settings;notify(parsed.note??'Crosshair imported. Extra menu settings keep their current values.');const codeKeys=Object.keys(result).filter(k=>k.startsWith('cl_crosshair')&&!['cl_crosshair_friendly_warning','cl_crosshair_sniper_width'].includes(k)||k.startsWith('cl_ironsight'));result={...s,...Object.fromEntries(codeKeys.map(k=>[k,result![k]]))};}else{result=importCommands(importText,s);notify('Current CS2 config settings imported.');}load(result);remember(result);setImportError('');setModal(null);}catch(error){setImportError(message(error));}}
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();void copy(commands(s),'Console commands');remember();}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);});
  const validPath=location.pathname==='/'||location.pathname==='/custom'||(/^\/(CS[A-Za-z0-9]{44}|CSGO(-[A-Za-z0-9]{5}){5})$/.test(location.pathname)&&!start.current.error);
  useEffect(()=>{if(location.pathname==='/custom')history.replaceState(null,'','/'+location.search+location.hash);},[]);
  if(!validPath)return <main className="not-found"><Crosshair size={52}/><h1>Crosshair not found</h1><p>This link does not point to a crosshair.</p><a href="/">Open the studio</a></main>;
  const visibleFields=styleFields(s);
  return <>
    <header className="header"><a className="brand" href="/" aria-label="delli.cc home"><Crosshair size={27}/><strong>delli<span>.cc</span></strong><span className="brand-divider"/><span className="brand-subtitle">CROSSHAIR STUDIO</span></a><nav className="menu-nav" aria-label="Studio menu"><button className="active" aria-current="page" onClick={()=>{setTab('all');document.querySelector('.page-heading')?.scrollIntoView({behavior:'smooth'});}}>Crosshair / Scopes</button><button onClick={()=>setModal('library')}>Library</button><button onClick={()=>setModal('help')}>Guide</button></nav><div className="header-actions"><span className="build-badge"><i/>CS2 CROSSHAIR EDITOR</span><button onClick={()=>setModal('library')}><Bookmark size={16}/>Library<span className="count">{library.length}</span></button><button className="icon-button" aria-label="Help and instructions" onClick={()=>setModal('help')}><HelpCircle size={19}/></button></div></header>
    <div className="page-heading"><div><p className="eyebrow">COUNTER-STRIKE 2</p><h1>Crosshair / Scopes <span className="new-badge">NEW SYSTEM</span></h1><p className="intro">Your crosshair. Every detail.</p></div><label className="theme-picker">Appearance<select aria-label="Appearance" value={theme} onChange={e=>setTheme(e.target.value)}><option value="cs2">CS2</option><option value="tactical">Tactical</option><option value="crimson">Crimson</option></select></label></div>
    <main className="workspace">
      <section className="preview-section" aria-label="Crosshair preview"><div className="preview-toolbar"><span><span className="live-dot"/>LIVE PREVIEW</span><div><select aria-label="Preview mode" value={previewMode} onChange={e=>setPreviewMode(e.target.value as PreviewMode)}><option value="crosshair">Crosshair</option><option value="scope">Scope dot</option></select><button className="fullscreen-button" aria-label="Fullscreen game-size preview" onClick={()=>void toggleFullscreen()}><Maximize size={15}/><span>Fullscreen</span></button><span className="toolbar-divider"/><div className="zoom-buttons">{[1,2,4,8].map(n=><button key={n} className={zoom===n?'active':''} onClick={()=>setZoom(n)} aria-label={`${n}x preview zoom`} aria-pressed={zoom===n}>{n}×</button>)}</div></div></div>
      <div ref={mapRef} className="map-preview" style={{backgroundImage:`url(/maps/${maps[map]}.webp)`}}><div className="map-label"><span>{mapNames[map]}</span><small>CROSSHAIR PREVIEW</small></div><Preview settings={s} zoom={zoom} targetHeight={effectiveHeight||undefined} dynamic={dynamic} mode={previewMode} phase={phase} fit={fit} inspectSplit={inspectSplit} paused={modal!==null} onStatus={setPreviewStatus}/><button className="map-arrow previous" aria-label="Previous map" onClick={()=>setMap((map+6)%7)}><ChevronLeft size={28}/></button><button className="map-arrow next" aria-label="Next map" onClick={()=>setMap((map+1)%7)}><ChevronRight size={28}/></button><div className="preview-actions">{fullscreen&&<button className="exit-fullscreen" aria-label="Exit fullscreen preview" onClick={()=>void toggleFullscreen()}><Minimize size={15}/>Exit fullscreen</button>}<button onClick={()=>setDynamic(!dynamic)}>{dynamic?<Pause size={13}/>:<Play size={13}/>} {dynamic?'Stop':'Start'} Dynamic Preview</button><div><button onClick={()=>{setImportError('');setModal('share');}}><ArrowUpRight size={14}/>Share or Import</button><button aria-label="Undo Changes" onClick={goBack} disabled={!undo.length}><Undo2 size={14}/><span>Undo Changes</span></button><button aria-label="Reset" onClick={reset}><RotateCcw size={14}/><span>Reset</span></button></div></div></div>
      <div className="preview-caption"><span>{effectiveHeight?`${zoom}× ${zoom===1?'game-size estimate':'inspection'} · ${effectiveHeight}p target · ${s.cl_crosshair_screen_height}p reference`:`${zoom}× CSS-pixel inspection`} · {previewStatus.scale.toFixed(2)} CSS px per unit</span><span>Centered on the preview · geometry is approximate</span></div>
      <div className="preview-inspection"><div className="preview-controls"><label>Preview scale<select aria-label="Preview scale" value={targetHeight} onChange={e=>setTargetHeight(Number(e.target.value))}><option value="-1">Monitor size (estimated)</option><option value="0">CSS pixels</option><option value="1080">Estimated 1080p</option><option value="1440">Estimated 1440p</option><option value="2160">Estimated 2160p</option></select></label>{targetHeight===-1&&<label>Display height<input className="display-height" aria-label="Display height in physical pixels" type="number" min="240" max="8640" step="1" value={displayHeightDraft??String(displayHeight||display.height)} onChange={e=>{setDisplayHeightDraft(e.target.value);const value=Number(e.target.value);if(Number.isInteger(value)&&value>=240&&value<=8640)setDisplayHeight(value);}} onBlur={()=>setDisplayHeightDraft(null)} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/>px</label>}<label><input type="checkbox" checked={fit} onChange={e=>setFit(e.target.checked)}/>Fit crosshair in preview</label><label>Inspection phase<input type="range" aria-label="Inspection phase" min="0" max="1" step="0.01" value={phase} onChange={e=>{setDynamic(false);setPhase(Number(e.target.value));}}/></label>{s.cl_crosshairstyle===2&&<label><input type="checkbox" checked={inspectSplit} onChange={e=>setInspectSplit(e.target.checked)}/>Inspect split arms</label>}<span aria-live="polite">{previewStatus.clipped?"Crosshair exceeds preview bounds. Enable fit to see the full shape.":fit?"Fit view may reduce magnification; exported settings are unchanged.":effectiveHeight?"Estimated target-resolution size; game-pixel calibration is pending.":"Reference height is exported metadata in CSS-pixel mode."}</span><span className="display-note">Display estimate {display.width} × {display.height} · pixel ratio {display.dpr.toFixed(2)}. Correct display height if needed. Fullscreen centers the crosshair on the screen. At 1×, image size does not shrink the crosshair; 2×–8× magnify it for editing.</span></div><div className="detail-preview"><span>4× detail</span><div><Preview settings={s} zoom={4} targetHeight={effectiveHeight||undefined} mode={previewMode} phase={phase} inspectSplit={inspectSplit} fit decorative paused/></div></div></div>
      </section>
      <div className="editor"><nav className="section-nav" aria-label="Crosshair sections">{[['all','All settings'],['style','Style'],['crosshair','Crosshair']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)} aria-pressed={tab===id}>{label}</button>)}</nav>
      {(tab==='all'||tab==='style')&&<section className="settings-section"><div className="section-title"><h2>Style Settings</h2><span>01</span></div><Row field={visibleFields[0]} s={s} set={change}/><ColorRow s={s} set={change}/><Row field={visibleFields[1]} s={s} set={change}/>{s.cl_crosshair_drawoutline!==0&&<ColorRow s={s} set={change} outline/>}{visibleFields.slice(2).map(field=><Row key={field.key} field={field} s={s} set={change}/>)}<div className="pixel-note"><SlidersHorizontal size={13}/><span>Length, thickness and gap use pixels. CS2 rescales them when your resolution changes. Gap values range from -10 to 128 pixels.</span></div></section>}
      {(tab==='all'||tab==='crosshair')&&<section className="settings-section"><div className="section-title"><h2>Crosshair Settings</h2><span>02</span></div>{crosshairFields.filter(f=>f.key!=='cl_observed_bot_crosshair'||s.cl_show_observer_crosshair===2).map(field=><Row key={field.key} field={field} s={s} set={change}/>)}</section>}
      <div className="editor-footer"><span>Changes are saved on this device.</span><button onClick={reset}><RotateCcw size={14}/>Reset crosshair</button></div>
    </div>
    <aside className="sidebar"><section className="export-card"><div className="card-heading"><FileCode2 size={18}/><h2>Take it into the game</h2></div><label className="field-label" htmlFor="share-code">CS2 SHARE CODE<span className="current-tag">CURRENT FORMAT</span></label><div className="code-box"><textarea id="share-code" readOnly value={code} aria-label="Current CS2 share code"/><button className="icon-button" aria-label="Copy share code" onClick={()=>{void copy(code,'Share code');remember();}}><Copy size={17}/></button></div><p className="code-hint">Settings → Crosshair / Scopes → Share or Import</p><button className="primary-button full" onClick={()=>{void copy(code,'Share code');remember();}}><Copy size={16}/>Copy crosshair code<ArrowUpRight size={16}/></button><div className="split-actions"><button onClick={()=>{void copy(shareLink(),'Share link');remember();}}><Link size={15}/>Copy link</button><button onClick={exportCfg}><Download size={15}/>Download .cfg</button></div><div className="card-separator"/><label className="field-label" htmlFor="alias">ALIAS NAME<span>OPTIONAL</span></label><input id="alias" className="text-input" placeholder="e.g. my_crosshair" value={alias} maxLength={48} onChange={e=>setAlias(e.target.value)} aria-invalid={!!aliasError} aria-describedby="alias-hint"/><p id="alias-hint" className={aliasError?'error-text':'code-hint'}>{aliasError||'Switch crosshairs by typing this name in the console.'}</p><button className="full quiet-button" disabled={!!aliasError} onClick={()=>void copy(autoexec(s,alias),'Autoexec shortcut')}><Copy size={14}/>Copy autoexec shortcut</button><details className="instructions"><summary>Config installation instructions</summary><p>Place the downloaded file in <code>Counter-Strike Global Offensive/game/csgo/cfg</code>.</p><p>{alias.trim()?'Add the shortcut below to autoexec.cfg, then type your alias in the CS2 console.':'Type exec crosshair.cfg in the CS2 console.'}</p>{alias.trim()&&!aliasError&&<code>{autoexec(s,alias)}</code>}<p>Share codes contain style and scope dot settings. The config and website link also include spectator, grenade and sniper preferences.</p></details><div className="card-separator"/><details className="console-details"><summary>Console commands <span>{Object.keys(s).length} settings</span></summary><textarea readOnly value={commands(s).split('; ').join('\n')} aria-label="Generated console commands"/></details><button className="full quiet-button" onClick={()=>{void copy(commands(s),'Console commands');remember();}}><Copy size={14}/>Copy console commands<kbd>Ctrl ↵</kbd></button></section>
    <section className="presets-card"><div className="card-heading"><Crosshair size={17}/><h2>A starting point</h2></div><div className="preset-grid">{presets.map(preset=><button className="preset" key={preset.name} onClick={()=>{load(preset.settings);notify(`${preset.name} preset loaded.`);}}><div className="preset-preview"><Preview settings={preset.settings} zoom={1} decorative/></div><span>{preset.name}</span></button>)}</div></section>
    <section className="save-card"><div className="card-heading"><Bookmark size={17}/><h2>Keep this crosshair</h2></div><label className="sr-only" htmlFor="saved-name">Crosshair name</label><input id="saved-name" className="text-input" value={savedName} maxLength={80} onChange={e=>setSavedName(e.target.value)}/><button className="full quiet-button" onClick={()=>{if(!savedName.trim()){notify('Give your crosshair a name.');return;}if(library.filter(i=>i.favorite).length>=50){notify('Your library has 50 favorites. Remove one before saving another.');return;}remember(s,savedName.trim(),true);notify('Crosshair saved to favorites.');}}><Plus size={15}/>Save to favorites</button><button className="library-link" onClick={()=>setModal('library')}>Open your library<ArrowUpRight size={14}/></button></section>
    {guide&&<section className="guide-card"><button className="icon-button close-guide" aria-label="Dismiss first-run guide" onClick={()=>{setGuide(false);write('guide-dismissed',true);}}><X size={14}/></button><p className="eyebrow">FIRST TIME HERE?</p><h3>Make it yours.</h3><p>Pick a style, tune the preview, then copy the code into CS2. Use a config to carry every menu setting with you.</p></section>}
    <p className="privacy-note"><span className="live-dot"/>Local by design. Your drafts, aliases and library stay in your browser.</p></aside></main>
    <footer className="site-footer"><span>delli.cc <span className="footer-divider">/</span> A crosshair that feels like yours.</span><span>Independent tool. Not affiliated with Valve.</span></footer>
    <div className="mobile-actions"><button onClick={()=>void copy(code,'Share code')}><Copy size={15}/>Copy code</button><button onClick={exportCfg}><Download size={15}/>.cfg</button><button onClick={()=>setModal('share')}><Upload size={15}/>Import</button></div>
    {toast&&<div className="toast" role="status"><Check size={16}/><span>{toast}</span><button className="icon-button" aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={14}/></button></div>}
    <dialog ref={dialogRef} onCancel={()=>setModal(null)} onClick={e=>{if(e.target===e.currentTarget)setModal(null);}} className={`modal ${modal==='library'?'library-modal':''}`}><div className="modal-header"><h2>{modal==='share'?'Share or Import':modal==='library'?'Your crosshair library':'Using the studio'}</h2><button className="icon-button" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={20}/></button></div>
    {modal==='share'&&<div className="modal-content"><p>Paste a current <code>CS</code> code, an older <code>CSGO-</code> code, or console commands.</p><label className="field-label" htmlFor="import-text">CROSSHAIR CODE OR CONFIG</label><textarea id="import-text" className="import-area" value={importText} onChange={e=>setImportText(e.target.value)} placeholder="CS… or cl_crosshairstyle 4; …"/><div className="import-tools"><button onClick={async()=>{try{setImportText(await navigator.clipboard.readText());}catch{setImportError('Clipboard access is unavailable. Paste into the box manually.');}}}><Copy size={14}/>Paste clipboard</button><button onClick={()=>cfgInput.current?.click()}><Upload size={14}/>Open .cfg</button></div><label className="legacy-resolution">Old code reference height<select aria-label="Old code reference height" value={legacyHeight} onChange={e=>setLegacyHeight(Number(e.target.value))}>{[720,768,960,1080,1440,2160].map(n=><option key={n} value={n}>{n}px</option>)}</select></label><p className="section-note">Pre-update conversion is approximate. Choose the resolution you used and check the result in the game.</p>{importError&&<p className="error-text" role="alert">{importError}</p>}<div className="modal-buttons"><button onClick={()=>void copy(code,'Share code')}>Copy your code</button><button className="primary-button" onClick={doImport}>Import crosshair<ArrowUpRight size={15}/></button></div></div>}
    {modal==='library'&&<div className="modal-content"><div className="library-tools"><div className="search-box"><Search size={16}/><input aria-label="Search crosshairs" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or code…"/></div><select aria-label="Library filter" value={libraryFilter} onChange={e=>setLibraryFilter(e.target.value)}><option value="all">All crosshairs</option><option value="favorites">Favorites</option><option value="history">Recent history</option></select></div><p className="section-note">Up to 50 favorites and 20 recent crosshairs. Stored on this device.</p><div className="library-list">{library.filter(item=>(libraryFilter==='all'||(libraryFilter==='favorites'?item.favorite:!item.favorite))&&`${item.name} ${encode(item.settings)}`.toLowerCase().includes(search.toLowerCase())).map(item=><div className="library-item" key={item.id}><div className="library-preview"><Preview settings={item.settings} zoom={2} decorative fit/></div><div className="library-info">{editing===item.id?<input autoFocus aria-label="Rename crosshair" value={item.name} maxLength={80} onChange={e=>setLibrary(prev=>prev.map(i=>i.id===item.id?{...i,name:e.target.value}:i))} onBlur={()=>{if(!item.name.trim())setLibrary(prev=>prev.map(i=>i.id===item.id?{...i,name:'Untitled crosshair'}:i));setEditing(null);}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/>:<strong>{item.name}</strong>}<code>{encode(item.settings).slice(0,18)}…</code></div><div className="library-item-actions"><button onClick={()=>{load(item.settings);setAlias(item.alias);setModal(null);notify(`${item.name} loaded.`);}}>Load</button><button className="icon-button" aria-label={`Copy ${item.name}`} onClick={()=>void copy(encode(item.settings),'Share code')}><Copy size={15}/></button><button className="icon-button" aria-label={`Rename ${item.name}`} onClick={()=>setEditing(item.id)}><Pencil size={15}/></button><button className={`icon-button ${item.favorite?'favorite':''}`} aria-label={`${item.favorite?'Unfavorite':'Favorite'} ${item.name}`} onClick={()=>{if(!item.favorite&&library.filter(i=>i.favorite).length>=50){notify('Favorite limit reached.');return;}setLibrary(prev=>limitLibrary(prev.map(i=>i.id===item.id?{...i,favorite:!i.favorite}:i)));}}><Star size={15}/></button><button className="icon-button" aria-label={`Remove ${item.name}`} onClick={()=>setLibrary(prev=>prev.filter(i=>i.id!==item.id))}><Trash2 size={15}/></button></div></div>)}{!library.length&&<div className="empty-library"><Bookmark size={32}/><h3>Your collection starts here.</h3><p>Save a favorite, import a code, or export a crosshair to see it here.</p></div>}</div><div className="modal-buttons"><button onClick={()=>backupInput.current?.click()}><Upload size={15}/>Restore backup</button><button onClick={()=>download(JSON.stringify({version:1,entries:library},null,2),'delli-crosshair-library.json','application/json')}><Download size={15}/>Export library</button></div></div>}
    {modal==='help'&&<div className="modal-content help-content"><h3>From the studio to CS2</h3><ol><li>Choose a style and adjust its settings.</li><li>Copy the CS2 share code.</li><li>In CS2, open Settings → Crosshair / Scopes → Share or Import. Paste and import.</li></ol><h3>Configs and aliases</h3><p>Download the .cfg file into the game's <code>game/csgo/cfg</code> directory. An alias shortcut belongs in <code>autoexec.cfg</code> and loads that file when you type the alias.</p><h3>Preview accuracy</h3><p>The preview uses real game backgrounds. CSS-pixel mode shows editor magnification. Estimated resolution modes scale by target height divided by exported reference height and convert physical pixels through the display pixel ratio; this mapping has not been calibrated against game captures. Dynamic motion, recoil, quadrant geometry and scope rendering are browser approximations. The animation exercises the configured spread limit; it does not model weapon inaccuracy, spread or the game's 64-pixel baseline. Verify the final crosshair in CS2.</p><h3>Give yourself a note</h3><p>Feedback stays on this device.</p><div className="rating">{[1,2,3,4,5].map(n=><button aria-label={`Rate ease of use ${n} out of 5`} aria-pressed={rating===n} className={n===rating?'active':''} key={n} onClick={()=>{setRating(n);write('rating',n);}}>{n}</button>)}</div><textarea aria-label="Local feedback note" className="import-area" placeholder="A note for next time…" maxLength={1000} value={note} onChange={e=>{setNote(e.target.value);write('feedback-note',e.target.value);}}/><a className="issue-link" href={`https://github.com/Softhe/cs2-crosshair/issues/new?title=${encodeURIComponent('Crosshair studio feedback')}&body=${encodeURIComponent('Feedback about the new crosshair studio.\n\nDescribe the issue here. No settings or local data have been attached.')}`} target="_blank" rel="noreferrer">Open an issue draft<ArrowUpRight size={15}/></a><p className="section-note">The issue draft contains no crosshair, alias, library or feedback data. Review it before submitting.</p></div>}
    </dialog>
    <input ref={backupInput} className="sr-only" type="file" accept=".json,application/json" aria-label="Library backup file" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>500000)throw Error('Backup is too large.');const data=JSON.parse(await file.text());if(data.version!==1)throw Error('Unsupported backup version.');const entries=validateLibrary(data.entries);if(entries.filter(i=>i.favorite).length>50||entries.filter(i=>!i.favorite).length>20)throw Error('Backup exceeds library limits.');setLibrary(prev=>{const combined=[...entries,...prev];return [...combined.filter(i=>i.favorite).slice(0,50),...combined.filter(i=>!i.favorite).slice(0,20)];});notify('Backup restored. Existing entries were retained.');}catch(error){notify(message(error));}}}/>
    <input ref={cfgInput} className="sr-only" type="file" accept=".cfg,.txt,.vcfg" aria-label="Crosshair config file" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>200000){setImportError('Config is too large.');return;}setImportText(await file.text());}}/>
  </>;
}
createRoot(document.getElementById('root')!).render(<App/>);
